site_name: Template de Documentação
theme:
  name: material
  language: pt-BR

nav:
  - Home: index.md
  - Coinsurance:
      - Visão geral do fluxo: coinsurance/index.md
      - Apólice:
          - Visão geral: coinsurance/apolice/index.md
          - Fluxos:
              - Emissão da Apólice (Master/Certificate): coinsurance/apolice/fluxos/emissao-apolice-master-certificate.md
              - Recebimento do Prêmio (PREMRECEB): coinsurance/apolice/fluxos/recebimento-premio-premreceb.md
          - PREMIT: coinsurance/apolice/premit.md
          - PREMREC: coinsurance/apolice/premrec.md
          - PREMRECEB: coinsurance/apolice/premreceb.md
          - RESPREM: coinsurance/apolice/resprem.md
          - De/Para:
              - PREMIT: coinsurance/apolice/depara/premit.md
              - PREMREC: coinsurance/apolice/depara/premrec.md
              - PREMRECEB: coinsurance/apolice/depara/premreceb.md
              - RESPREM: coinsurance/apolice/depara/resprem.md
              - Mapeamentos internos: coinsurance/apolice/depara/mapeamentos-internos.md
      - Sinistro:
          - Visão geral: coinsurance/sinistro/index.md
          - SINAV: coinsurance/sinistro/sinav.md
          - SINPEND: coinsurance/sinistro/sinpend.md
          - SINPAG: coinsurance/sinistro/sinpag.md
          - De/Para:
              - SINAV: coinsurance/sinistro/depara/sinav.md
              - SINPEND: coinsurance/sinistro/depara/sinpend.md
              - SINPAG: coinsurance/sinistro/depara/sinpag.md
      - Retornos (RO BMG):
          - Visão geral: coinsurance/retornos/index.md
          - PREMAC: coinsurance/retornos/premac.md
          - PREMRECAC: coinsurance/retornos/premrecac.md
          - PREMRECEBC: coinsurance/retornos/premrecebc.md
          - SINAVAC: coinsurance/retornos/sinavac.md
          - SINPENDAC: coinsurance/retornos/sinpendac.md
          - SINPAGAC: coinsurance/retornos/sinpagac.md
plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - attr_list
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
